name: Setup
runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: npm
        check-latest: false

    - name: Cache dependencies
      uses: actions/cache@v4
      id: npm-cache
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shel: sh
      run: npm ci --no-audit --no-fund
